version: '3.7'

services:
  app:
    image: abidsutsna/tokonyadia:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://container_db:3306/tokonyadia_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - container_db
  
  container_db:
    image: mysql:latest
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: "3306:3306"
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tokonyadia_db
      MYSQL_PASSWORD: secret
       