server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/tokonyadia_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

      
    # database-platform: org.hibernate.dialect.MySQL8Dialect